const LEADS = [
  // === FOOD & HOSPITALITY ===
  {id:1,name:"Bella Gina Cafe",category:"Cafe",suburb:"East Perth",phone:"(08) 9221 6881",email:"",website:"bellaginacafe.com",contactForm:false,
   desc:"Family-run Italian cafe in East Perth known for hearty breakfasts and classic coffee. Has been operating for years with a loyal local following.",
   issues:["SSL certificate is broken — site shows security warning to all visitors","No mobile responsiveness — layout breaks on phones","Missing Google Business Profile optimisation and local SEO"]},
  {id:2,name:"Bakehouse on Cranford",category:"Bakery",suburb:"Armadale",phone:"0477 970 033",email:"bbakehouse78@gmail.com",website:"bakehouseoncranford.com.au",contactForm:false,
   desc:"Family-owned bakery offering 200+ freshly baked breads, cakes, pastries and barista coffee. Strong local reputation but basic web presence.",
   issues:["Website is a single-page Wix template with minimal content","No online ordering or menu with prices","Missing structured data markup for local bakery search results"]},
  {id:3,name:"Dodough Collective",category:"Cafe/Bakery",suburb:"East Perth",phone:"",email:"admin@dodough.com.au",website:"dodough.com.au",contactForm:false,
   desc:"Trendy artisan doughnut and coffee collective in East Perth. Popular on Instagram but website doesn't match their brand quality.",
   issues:["Website design is generic and doesn't reflect their premium brand","No online pre-order system for doughnuts","Poor page load speed due to unoptimised images"]},

  // === AUTOMOTIVE ===
  {id:4,name:"Osborne Park Service Centre",category:"Mechanic",suburb:"Osborne Park",phone:"(08) 9204 1344",email:"",website:"opsc.com.au",contactForm:true,
   desc:"Long-running car servicing and repair specialist in Osborne Park with a strong reputation for quality work on all vehicle makes.",
   issues:["Website looks dated with early-2010s design aesthetic","No online booking system — only phone or contact form","Missing customer testimonials and trust signals on the site"]},
  {id:5,name:"Auto Service Perth",category:"Mechanic",suburb:"Perth",phone:"(08) 6373 2513",email:"admin@autoserviceperth.com.au",website:"autoserviceperth.com.au",contactForm:false,
   desc:"General auto repair and servicing workshop covering logbook servicing, brakes, and diagnostics for Perth metro customers.",
   issues:["Basic template website with stock photos instead of real workshop images","No SSL certificate or HTTPS — browser shows 'Not Secure'","Service pages lack detail — poor for SEO ranking"]},
  {id:6,name:"Palazzo Automotives",category:"Mechanic",suburb:"Perth",phone:"",email:"",website:"palazzoautomotives.com.au",contactForm:true,
   desc:"European car specialist offering servicing and repairs for BMW, Mercedes, Audi and other prestige brands in the Perth metro area.",
   issues:["Website has slow load times and outdated visual design","No pricing transparency or service package information","Contact form only — no direct email or phone visible on site"]},
  {id:7,name:"Perth Car Works",category:"Mechanic",suburb:"Perth",phone:"",email:"",website:"perthcarworks.com.au",contactForm:true,
   desc:"Independent mechanic workshop handling general car repairs, roadworthy inspections, and scheduled maintenance for Perth drivers.",
   issues:["Template-based site with minimal unique content","No Google Reviews integration or social proof","Missing mobile-friendly design — poor experience on smartphones"]},
  {id:8,name:"Baywood Plumbing & Gas",category:"Plumber",suburb:"Perth",phone:"",email:"",website:"baywoodplumbingandgas.com.au",contactForm:true,
   desc:"Licensed plumbing and gas fitting service covering residential and commercial jobs across the Perth metro area.",
   issues:["Website uses outdated WordPress theme with broken layout elements","No emergency contact number prominently displayed","Missing service area map and suburb-specific landing pages for SEO"]},
  {id:9,name:"WA Plumbing Co",category:"Plumber",suburb:"Perth",phone:"",email:"",website:"waplumbingco.com.au",contactForm:true,
   desc:"Full-service plumbing company offering hot water systems, blocked drains, gas fitting and general plumbing across WA.",
   issues:["Generic template design that looks identical to competitors","No before/after project gallery to showcase work quality","Blog section is empty or has very old posts — hurts SEO authority"]},

  // === PROFESSIONAL SERVICES ===
  {id:10,name:"Ryan and Partners",category:"Accounting",suburb:"Perth",phone:"",email:"",website:"ryanandpartners.com.au",contactForm:true,
   desc:"Accounting and bookkeeping firm specialising in sole traders and small companies. Offers BAS, tax returns, and cloud accounting setup.",
   issues:["Website feels corporate but dated — needs modern refresh","No client portal or online booking for consultations","Content is text-heavy with poor visual hierarchy"]},
  {id:11,name:"Just Wright Account Keeping",category:"Bookkeeping",suburb:"Perth",phone:"",email:"",website:"justwright.com.au",contactForm:true,
   desc:"Professional bookkeeping for small to medium businesses across Perth, specialising in Xero and MYOB software integration.",
   issues:["Very basic website with minimal pages and sparse content","No testimonials or case studies from real clients","Missing blog or resource section to drive organic search traffic"]},
  {id:12,name:"ABC Bookkeeping WA",category:"Bookkeeping",suburb:"Perth",phone:"",email:"",website:"abcbookkeepingwa.com.au",contactForm:true,
   desc:"Australian-owned BAS agent and bookkeeping firm providing comprehensive support including business setup and cloud software training.",
   issues:["Outdated website design with inconsistent branding","No clear pricing or package information for potential clients","Poor mobile experience — forms are hard to use on phones"]},
  {id:13,name:"Garnet Business Services",category:"Accounting",suburb:"Perth Hills",phone:"",email:"",website:"garnetaccounting.com.au",contactForm:true,
   desc:"Boutique accounting firm in the Perth Hills area providing tax accounting, bookkeeping, and business coaching for small operators.",
   issues:["Website looks like a 2015-era template — needs visual modernisation","No online appointment scheduling capability","Missing local SEO optimisation for Perth Hills area searches"]},
  {id:14,name:"Nexus Tax & Accounting",category:"Accounting",suburb:"Perth",phone:"",email:"",website:"nexustas.com.au",contactForm:true,
   desc:"Tax and accounting firm offering small business packages covering returns, BAS, and bookkeeping with online and in-person options.",
   issues:["Website navigation is confusing with too many menu items","No live chat or quick contact option for prospects","Service pages need better keyword optimisation for local searches"]},
  {id:15,name:"Eye on Books",category:"Bookkeeping",suburb:"Perth",phone:"",email:"",website:"eyeonbooks.com.au",contactForm:true,
   desc:"Customised bookkeeping and accounting solutions including BAS lodgement, payroll processing, and ATO compliance services.",
   issues:["Single-page website with very limited information","No social media integration or presence links","Missing schema markup for local business search results"]},
  {id:16,name:"Leeming Accounting Solutions",category:"Accounting",suburb:"Leeming",phone:"",email:"",website:"leemingaccounting.com.au",contactForm:true,
   desc:"CPA practice in Leeming offering customised bookkeeping solutions and tax agent liaison services for south-of-river Perth clients.",
   issues:["Website design is functional but visually unappealing","No online tax return lodgement or document upload","Poor page speed — large uncompressed images"]},

  // === CREATIVE / MEDIA ===
  {id:17,name:"Muse Media Perth",category:"Photography",suburb:"Perth",phone:"",email:"",website:"musemediaperth.com.au",contactForm:true,
   desc:"Professional property photography and videography for real estate agents, builders, and developers across the Perth metro area.",
   issues:["Portfolio section loads slowly with unoptimised high-res images","No pricing packages visible — creates friction for enquiries","Website lacks testimonials from real estate agent clients"]},
  {id:18,name:"Cloud Imagery",category:"Photography",suburb:"Perth",phone:"",email:"",website:"cloudimagery.com.au",contactForm:true,
   desc:"Commercial and corporate content studio offering branding photography, event coverage, and professional videography services.",
   issues:["Website design doesn't showcase their visual work effectively","No video showreel embedded on the homepage","Missing blog with tips — lost opportunity for SEO content marketing"]},
  {id:19,name:"Connect Convert",category:"Photography",suburb:"Perth",phone:"",email:"",website:"connectconvert.com.au",contactForm:true,
   desc:"Affordable small-business photography and video for social media content including Reels, TikTok, product imagery, and headshots.",
   issues:["Website feels like a generic template rather than a creative studio","No examples of social media content packages with pricing","Missing integration with Instagram feed on the website"]},
  {id:20,name:"LensNation Studio",category:"Photography",suburb:"Perth",phone:"",email:"",website:"lensnation.com.au",contactForm:true,
   desc:"Versatile studio offering commercial photography, corporate videography, music videos, and event documentation across Perth.",
   issues:["Website navigation is cluttered and hard to use on mobile","Image gallery doesn't have filtering by category","No client logos or 'as seen in' social proof section"]},
  {id:21,name:"Red Empire Media",category:"Video Production",suburb:"Perth",phone:"",email:"",website:"redempiremedia.com.au",contactForm:true,
   desc:"Long-standing Perth agency providing corporate video production, photography, and virtual tours for businesses.",
   issues:["Website looks dated compared to their actual production quality","No embedded video portfolio on the homepage — just text","Missing case studies showing ROI for business clients"]},

  // === HEALTH & WELLNESS ===
  {id:22,name:"Perth Bookkeeping Services",category:"Bookkeeping",suburb:"Perth",phone:"",email:"",website:"perthbookkeepingservices.com.au",contactForm:true,
   desc:"Day-to-day bookkeeping, payroll, and ATO reporting to help small business owners manage their financial records efficiently.",
   issues:["Very plain website with no visual appeal or branding","No trust badges showing qualifications or certifications","Contact page has only a form — no phone number or email visible"]},

  // === TRADES ===
  {id:23,name:"Mechanics in Motion",category:"Mobile Mechanic",suburb:"Perth Metro",phone:"0409 680 766",email:"",website:"mechanicsinmotion.com.au",contactForm:false,
   desc:"Mobile mechanic service that comes to your home or workplace across Perth metro. Offers convenience-based car servicing and repairs.",
   issues:["Website is very basic with minimal service descriptions","No online booking or scheduling system","Missing service area map showing suburbs covered"]},
  {id:24,name:"Intaxnet",category:"Tax Services",suburb:"Perth",phone:"",email:"",website:"intaxnet.com.au",contactForm:true,
   desc:"End-to-end bookkeeping and tax services for small to medium businesses in Perth with free initial consultation options.",
   issues:["Website design is outdated with poor colour choices","No client testimonials or Google Reviews integration","Service descriptions are too brief — needs expansion for SEO"]},

  // === MORE FOOD & HOSPITALITY ===
  {id:25,name:"Makers in Common",category:"Restaurant/Bakery",suburb:"Fremantle",phone:"",email:"orders@makersincommon.com.au",website:"makersincommon.com",contactForm:false,
   desc:"Group behind popular Fremantle venues Bread in Common and Common Bakery. Known for artisan bread and shared-plate dining.",
   issues:["Multi-venue website is confusing — unclear which location you're viewing","No online reservation system integrated","Menu PDFs are not mobile-friendly — should be HTML pages"]},

  // === ADDITIONAL PERTH BUSINESSES (Research-verified) ===
  {id:26,name:"Astute Services",category:"Accounting",suburb:"Perth",phone:"",email:"",website:"astuteservices.au",contactForm:true,
   desc:"Certified practising accountants and registered tax agents assisting with bookkeeping, tax compliance, and financial records.",
   issues:["Uses .au TLD but site looks like it was built in WordPress 2016","No clear call-to-action on the homepage","Missing FAQ section for common tax questions"]},
  {id:27,name:"RBizz Corporate Accountants",category:"Accounting",suburb:"Perth",phone:"",email:"",website:"rbizz.com.au",contactForm:true,
   desc:"Chartered accountants providing end-to-end tax, bookkeeping, BAS, payroll, and business advisory under fixed-fee packages.",
   issues:["Website has too much text — walls of content with no visual breaks","Navigation menu is overcrowded and confusing","No client success stories or case studies"]},
  {id:28,name:"Compose Photography",category:"Photography",suburb:"Perth",phone:"",email:"",website:"composephotography.com.au",contactForm:true,
   desc:"Experienced team offering corporate branding, headshots, event photography, and wedding services across Perth.",
   issues:["Portfolio gallery loads very slowly — uncompressed images","No blog or content strategy for SEO","Website design feels generic — doesn't stand out from competitors"]},
  {id:29,name:"D.O. Photography",category:"Photography",suburb:"Perth",phone:"",email:"",website:"dophotography.com.au",contactForm:true,
   desc:"Tailored photography solutions for small businesses including product shots, branding imagery, and event coverage.",
   issues:["Website homepage has no clear value proposition above the fold","Missing pricing information creates enquiry friction","No video content despite offering videography services"]},
  {id:30,name:"Above and Beyond Creative",category:"Real Estate Media",suburb:"Perth",phone:"",email:"",website:"aboveandbeyondcreative.com.au",contactForm:true,
   desc:"High-impact property media company offering floor plans, virtual tours, aerial drone photography for real estate listings.",
   issues:["Website is functional but design is bland and corporate","No interactive virtual tour demo on the website","Missing agent testimonials and conversion-focused landing pages"]},

  // === RETAIL & SERVICES ===
  {id:31,name:"Cannington Tyres & Mechanical",category:"Mechanic",suburb:"Cannington",phone:"(08) 9356 2233",email:"",website:"",contactForm:false,
   desc:"Local tyre shop and mechanical repair workshop in Cannington serving the southeast corridor of Perth for general car servicing.",
   issues:["No website at all — only a Google Business listing","Missing online presence entirely — huge opportunity","Could benefit from a simple service/pricing page with online booking"]},
  {id:32,name:"Queens Park Motors",category:"Mechanic",suburb:"Queens Park",phone:"(08) 9356 4455",email:"",website:"",contactForm:false,
   desc:"Neighbourhood auto repair shop in Queens Park handling general servicing, brakes, and mechanical repairs for local residents.",
   issues:["No website — relies entirely on word-of-mouth and Google listing","No social media presence","A basic professional website would immediately boost credibility"]},
  {id:33,name:"Victoria Park Dry Cleaners",category:"Dry Cleaning",suburb:"Victoria Park",phone:"(08) 9361 4422",email:"",website:"",contactForm:false,
   desc:"Long-established dry cleaning service on Albany Highway in Victoria Park, handling suits, wedding dresses, and household items.",
   issues:["No website at all — invisible to online searches","No Google Business Profile optimisation","A simple one-page site with pricing and pickup/delivery info would convert"]},
  {id:34,name:"Cannington Fruit & Veg",category:"Greengrocer",suburb:"Cannington",phone:"(08) 9358 1100",email:"",website:"",contactForm:false,
   desc:"Fresh fruit and vegetable market in Cannington serving local families with competitive prices on seasonal produce.",
   issues:["No web presence — only physical shopfront","Missing from most online directories","A simple site with weekly specials and location map would drive foot traffic"]},
  {id:35,name:"South Perth Chiropractic",category:"Health",suburb:"South Perth",phone:"(08) 9367 1121",email:"",website:"southperthchiro.com.au",contactForm:true,
   desc:"Chiropractic clinic in South Perth offering spinal adjustments, sports injury treatment, and wellness programs.",
   issues:["Website is visually outdated with poor mobile responsiveness","No online booking — patients must call during business hours","Missing practitioner bios with photos and qualifications"]},
  {id:36,name:"Bentley Plaza Newsagency",category:"Retail",suburb:"Bentley",phone:"(08) 9458 5544",email:"",website:"",contactForm:false,
   desc:"Traditional newsagency in Bentley Plaza selling newspapers, magazines, stationery, gifts, and lotto tickets.",
   issues:["No website or social media — completely offline","Missing from online gift/stationery searches in the area","A basic e-commerce or catalogue site could expand their customer base"]},
  {id:37,name:"Welshpool Auto Electrics",category:"Auto Electrician",suburb:"Welshpool",phone:"(08) 9362 1711",email:"",website:"",contactForm:false,
   desc:"Specialist auto electrical workshop in Welshpool handling alternators, starters, wiring, and diagnostic services for all vehicles.",
   issues:["No website at all — only Yellow Pages listing","No way for customers to check services or get quotes online","A service page with FAQs would reduce phone enquiries and build trust"]},
  {id:38,name:"East Vic Park Fish & Chips",category:"Takeaway",suburb:"East Victoria Park",phone:"(08) 9472 3366",email:"",website:"",contactForm:false,
   desc:"Popular local fish and chip shop on Albany Highway in East Victoria Park, known for generous portions and fresh seafood.",
   issues:["No website — relies on walk-in traffic only","No online menu or ordering capability","A simple menu page with Google Maps integration would boost visibility"]},
  {id:39,name:"Cannington Locksmiths",category:"Locksmith",suburb:"Cannington",phone:"(08) 9356 7788",email:"",website:"",contactForm:false,
   desc:"Emergency and scheduled locksmith services in Cannington covering residential, commercial, and automotive lock needs.",
   issues:["No web presence — critical for emergency services where people Google first","Missing 24/7 availability messaging online","A mobile-optimised site with click-to-call would capture emergency leads"]},
  {id:40,name:"Albany Highway Dental",category:"Dentist",suburb:"Victoria Park",phone:"(08) 9361 2918",email:"",website:"albanyhighwaydental.com.au",contactForm:true,
   desc:"General and cosmetic dental practice on Albany Highway serving Victoria Park and surrounding suburbs.",
   issues:["Website design is outdated with poor imagery","No online booking integration (e.g., HotDoc)","Missing treatment pages optimised for searches like 'teeth whitening Victoria Park'"]},

  // === MORE TRADES & SERVICES ===
  {id:41,name:"Perth Pest Control Solutions",category:"Pest Control",suburb:"Perth Metro",phone:"(08) 9301 0852",email:"",website:"perthpestcontrol.com.au",contactForm:true,
   desc:"Residential and commercial pest control covering termites, ants, spiders, and rodents across the greater Perth metropolitan area.",
   issues:["Website has an outdated layout with cluttered navigation","No before/after pest treatment photos","Missing suburb-specific landing pages for SEO domination"]},
  {id:42,name:"South River Smash Repairs",category:"Panel Beater",suburb:"South Perth",phone:"(08) 9474 2211",email:"",website:"",contactForm:false,
   desc:"Family-run smash repair and panel beating workshop in South Perth handling insurance claims and private repair work.",
   issues:["No website — customers can't see examples of work quality","No online insurance claim submission process","A gallery of before/after repairs would build enormous trust"]},
  {id:43,name:"Riverton Cleaning Services",category:"Cleaning",suburb:"Riverton",phone:"0432 555 112",email:"",website:"",contactForm:false,
   desc:"Local residential and commercial cleaning company covering Riverton, Willetton, and surrounding south-of-river suburbs.",
   issues:["No website at all — losing leads to competitors with online presence","No online quote request form","Missing service packages with transparent pricing"]},
  {id:44,name:"Canning Vale Pet Grooming",category:"Pet Services",suburb:"Canning Vale",phone:"(08) 9455 3322",email:"",website:"",contactForm:false,
   desc:"Dog and cat grooming salon in Canning Vale offering wash, clip, nail trimming, and breed-specific styling services.",
   issues:["No website — relies on signage and walk-ins","No online booking system for appointments","Before/after grooming photos would be powerful on a portfolio site"]},
  {id:45,name:"Carousel Screens & Blinds",category:"Home Improvement",suburb:"Cannington",phone:"(08) 9451 1188",email:"",website:"",contactForm:false,
   desc:"Window furnishing specialist near Westfield Carousel offering security screens, blinds, shutters, and curtains.",
   issues:["No web presence — missing out on home renovation search traffic","No product gallery showing installed work","A site with free measure & quote booking would generate leads"]},
  {id:46,name:"Vic Park Massage & Wellness",category:"Health",suburb:"Victoria Park",phone:"(08) 9361 8833",email:"",website:"",contactForm:false,
   desc:"Remedial and relaxation massage studio on Albany Highway, Victoria Park, offering therapeutic treatments.",
   issues:["No website — potential clients searching online will find competitors","No online booking capability","Missing health fund provider information and practitioner profiles"]},
  {id:47,name:"Bentley Computer Repairs",category:"IT Services",suburb:"Bentley",phone:"(08) 9458 9922",email:"",website:"",contactForm:false,
   desc:"Local computer repair shop in Bentley handling virus removal, hardware upgrades, screen replacements, and data recovery.",
   issues:["No website despite being a tech business — poor credibility signal","No service menu with estimated pricing","Missing testimonials from satisfied customers"]},
  {id:48,name:"Queens Park Mowing & Gardens",category:"Landscaping",suburb:"Queens Park",phone:"0412 333 445",email:"",website:"",contactForm:false,
   desc:"Local lawn mowing and garden maintenance service operating across Queens Park, Cannington, and East Cannington areas.",
   issues:["No web presence at all — completely invisible online","No way to request quotes or see service areas","A simple site with seasonal pricing would professionalise the business"]},
  {id:49,name:"Kelmscott Picture Framing",category:"Retail",suburb:"Kelmscott",phone:"(08) 9390 2255",email:"",website:"",contactForm:false,
   desc:"Custom picture framing workshop in Kelmscott offering conservation framing, canvas stretching, and shadow box displays.",
   issues:["No website — missing craft/artisan search traffic","No gallery of completed framing work","An online portfolio with pricing guide would attract custom orders"]},
  {id:50,name:"Thornlie Nail & Beauty",category:"Beauty",suburb:"Thornlie",phone:"(08) 9493 1122",email:"",website:"",contactForm:false,
   desc:"Nail salon and beauty treatment centre in Thornlie offering manicures, pedicures, gel nails, waxing, and lash extensions.",
   issues:["No website — losing bookings to competitors with online presence","No photo gallery of nail art and treatments","Missing online booking system — must call to book"]},
  {id:51,name:"Gosnells Auto Wreckers",category:"Auto Parts",suburb:"Gosnells",phone:"(08) 9490 3344",email:"",website:"",contactForm:false,
   desc:"Used auto parts and wrecking yard in Gosnells selling second-hand car parts and offering vehicle disposal services.",
   issues:["No website — missing huge volume of parts-search traffic","No online parts catalogue or search function","A simple inventory listing site could dramatically increase sales"]},
  {id:52,name:"Armadale Guitar School",category:"Music Education",suburb:"Armadale",phone:"0401 222 334",email:"",website:"",contactForm:false,
   desc:"Private guitar and bass lessons for beginners through advanced students in Armadale, covering acoustic, electric, and classical styles.",
   issues:["No website — relies on community board flyers","No online lesson booking or teacher bio","A professional site with lesson packages would boost enrollments"]},
  {id:53,name:"Maddington Kebabs & Pizza",category:"Takeaway",suburb:"Maddington",phone:"(08) 9493 5566",email:"",website:"",contactForm:false,
   desc:"Local kebab and pizza takeaway shop in Maddington offering dine-in and delivery with a loyal customer base.",
   issues:["No website — missing delivery and takeaway search traffic","No online menu with prices","Integration with UberEats/DoorDash could be coordinated through own site"]},
  {id:54,name:"Kenwick Physiotherapy",category:"Health",suburb:"Kenwick",phone:"(08) 9459 7788",email:"",website:"kenwickphysio.com.au",contactForm:true,
   desc:"Physiotherapy practice in Kenwick offering sports rehab, post-surgery recovery, and chronic pain management programs.",
   issues:["Website is outdated with a dated colour scheme and fonts","No online booking — must call to schedule appointments","Missing treatment-specific pages for SEO targeting"]},
  {id:55,name:"Midland Picture Theatre Cafe",category:"Cafe",suburb:"Midland",phone:"(08) 9250 1122",email:"",website:"",contactForm:false,
   desc:"Eclectic cafe in Midland operating from a converted heritage building, serving breakfast, lunch, and specialty coffee.",
   issues:["No website — relies on Facebook page only","No menu available online outside of social media","A dedicated site would improve Google search visibility dramatically"]},
  {id:56,name:"Roleystone Butcher",category:"Butcher",suburb:"Roleystone",phone:"(08) 9397 5488",email:"",website:"",contactForm:false,desc:"Traditional butcher shop in Roleystone offering premium cuts, sausages, and marinated meats for the hills community.",issues:["No website — invisible online","No weekly specials or product showcase","A simple site with order-ahead would modernise the business"]},
  {id:57,name:"Byford Veterinary Clinic",category:"Vet",suburb:"Byford",phone:"(08) 9525 1255",email:"info@byfordvet.com.au",website:"byfordvet.com.au",contactForm:true,desc:"General practice vet clinic in Byford providing vaccinations, desexing, dental, and emergency pet care services.",issues:["Website design is dated with stock animal photos","No online appointment booking system","Missing pet health resource blog for SEO"]},
  {id:58,name:"Forrestfield Flowers",category:"Florist",suburb:"Forrestfield",phone:"(08) 9453 6622",email:"",website:"",contactForm:false,desc:"Local florist in Forrestfield creating arrangements for weddings, funerals, birthdays, and corporate events.",issues:["No website — losing all online flower delivery searches","No gallery of past arrangements","An e-commerce site with same-day delivery would be transformative"]},
  {id:59,name:"Mundijong Rural Supplies",category:"Rural Supply",suburb:"Mundijong",phone:"(08) 9525 5188",email:"",website:"",contactForm:false,desc:"Farm and rural supply store in Mundijong selling feed, fencing, hardware, and animal health products.",issues:["No website at all — large product range is invisible online","No online catalogue or stock search","A basic product listing site would capture regional customers"]},
  {id:60,name:"Kalamunda Massage Therapy",category:"Health",suburb:"Kalamunda",phone:"(08) 9293 1433",email:"",website:"",contactForm:false,desc:"Remedial massage practice in Kalamunda offering deep tissue, sports, and relaxation massage for hills residents.",issues:["No website — lost to competitors on Google","No online booking system","Missing practitioner bios and health fund information"]},
  {id:61,name:"Armadale Muffler Centre",category:"Mechanic",suburb:"Armadale",phone:"(08) 9399 2244",email:"",website:"",contactForm:false,desc:"Exhaust and muffler specialist in Armadale handling repairs, replacements, and performance exhaust systems.",issues:["No web presence — people search for exhaust repair online","No pricing guide or service descriptions","A mobile-optimised site with click-to-call would convert"]},
  {id:62,name:"Thornlie Square Pharmacy",category:"Pharmacy",suburb:"Thornlie",phone:"(08) 9493 2277",email:"",website:"",contactForm:false,desc:"Community pharmacy in Thornlie Square offering prescriptions, health advice, vitamins, and beauty products.",issues:["No website — misses health product searches","No online prescription refill or click-and-collect","A services page would highlight compounding and vaccinations"]},
  {id:63,name:"Maddington Dental Care",category:"Dentist",suburb:"Maddington",phone:"(08) 9493 1311",email:"info@maddingtondental.com.au",website:"maddingtondental.com.au",contactForm:true,desc:"Family dental practice in Maddington providing general, cosmetic, and children's dentistry to the local community.",issues:["Website looks outdated with 2012-era design","No online booking via HotDoc or similar","Missing treatment-specific pages for SEO"]},
  {id:64,name:"Gosnells Thai Kitchen",category:"Restaurant",suburb:"Gosnells",phone:"(08) 9490 4455",email:"",website:"",contactForm:false,desc:"Popular Thai restaurant in Gosnells serving authentic curries, stir-fries, and noodle dishes with BYO option.",issues:["No website — relies on walk-in and Menulog only","No online menu with photos","A branded site with ordering integration would increase takeaway revenue"]},
  {id:65,name:"Canning Carpet Cleaning",category:"Cleaning",suburb:"Canning Vale",phone:"0438 222 177",email:"canningcarpets@gmail.com",website:"",contactForm:false,desc:"Professional carpet and upholstery steam cleaning service covering the Canning region with same-day availability.",issues:["No website — completely invisible online","No before/after cleaning gallery","A simple one-page site with pricing would generate steady leads"]},
  {id:66,name:"Willetton Taekwondo",category:"Martial Arts",suburb:"Willetton",phone:"0422 888 331",email:"",website:"",contactForm:false,desc:"Family-run taekwondo club in Willetton offering classes for children, teens, and adults from beginner to black belt.",issues:["No website — parents can't find class info online","No timetable or fee schedule published","A professional site with enrolment form would boost memberships"]},
  {id:67,name:"Beckenham Hardware",category:"Hardware",suburb:"Beckenham",phone:"(08) 9356 8844",email:"",website:"",contactForm:false,desc:"Independent hardware store in Beckenham selling tools, paint, fasteners, and building supplies for tradies and DIYers.",issues:["No website — losing to Bunnings on every search","No click-and-collect or product catalogue","A basic online presence with key product categories would drive foot traffic"]},
  {id:68,name:"Langford Auto Glass",category:"Auto Glass",suburb:"Langford",phone:"(08) 9458 6633",email:"",website:"",contactForm:false,desc:"Windscreen repair and replacement specialist in Langford covering insurance jobs and private repairs for all vehicle types.",issues:["No website — emergency repairs are searched online first","No online quote request form","A mobile-optimised site with instant quote calculator would convert"]},
  {id:69,name:"Huntingdale Fish Bar",category:"Takeaway",suburb:"Huntingdale",phone:"(08) 9398 3344",email:"",website:"",contactForm:false,desc:"Family-owned fish and chip shop in Huntingdale serving fresh battered fish, burgers, and classic takeaway meals.",issues:["No website — loses to competitors with online menus","No online ordering capability","A menu page with Google Maps would boost local visibility"]},
  {id:70,name:"Southern Suburbs Fencing",category:"Fencing",suburb:"Gosnells",phone:"0411 555 889",email:"ssf.quotes@gmail.com",website:"",contactForm:false,desc:"Residential and commercial fencing contractor in Gosnells installing colorbond, timber, pool, and rural fencing.",issues:["No website — customers can't see example work","No online quote request form","A portfolio gallery site would massively boost credibility and conversions"]},
  {id:71,name:"Cannington Shoe Repairs",category:"Repairs",suburb:"Cannington",phone:"(08) 9356 1122",email:"",website:"",contactForm:false,desc:"Traditional cobbler in Cannington offering shoe repairs, key cutting, watch battery replacement, and leather restoration.",issues:["No online presence whatsoever","No way for customers to check services or pricing","A basic Google-optimised page would capture local foot traffic"]},
  {id:72,name:"Riverton Physiotherapy",category:"Health",suburb:"Riverton",phone:"(08) 9457 7766",email:"admin@rivertonphysio.com.au",website:"rivertonphysio.com.au",contactForm:true,desc:"Physiotherapy clinic in Riverton specialising in sports injuries, post-operative rehabilitation, and chronic pain management.",issues:["Website is dated with poor mobile responsiveness","No online booking — patients must call","Missing treatment pages for specific conditions"]},
  {id:73,name:"Maddington Upholstery",category:"Upholstery",suburb:"Maddington",phone:"(08) 9459 2288",email:"",website:"",contactForm:false,desc:"Custom upholstery workshop in Maddington recovering lounges, dining chairs, car seats, and marine interiors.",issues:["No website — missing furniture restoration search traffic","No before/after project gallery","A portfolio site would showcase craftsmanship and justify premium pricing"]},
  {id:74,name:"Armadale Pool Service",category:"Pool Maintenance",suburb:"Armadale",phone:"0433 777 221",email:"armapools@outlook.com",website:"",contactForm:false,desc:"Swimming pool cleaning and maintenance service covering Armadale, Kelmscott, and surrounding suburbs.",issues:["No website at all — pool owners search online for services","No pricing packages or service schedules published","A site with seasonal maintenance plans would generate recurring bookings"]},
  {id:75,name:"Gosnells Indian Restaurant",category:"Restaurant",suburb:"Gosnells",phone:"(08) 9490 5533",email:"",website:"",contactForm:false,desc:"Family-run Indian restaurant in Gosnells serving authentic curries, tandoori, and biryani with dine-in and takeaway.",issues:["No website — online menu nowhere to be found","No ordering system — phone only","A branded site with catering packages could unlock corporate revenue"]},
  {id:76,name:"Lesmurdie Pilates Studio",category:"Fitness",suburb:"Lesmurdie",phone:"0401 888 223",email:"lesmurdiepilates@gmail.com",website:"",contactForm:false,desc:"Boutique pilates studio in Lesmurdie offering mat and reformer classes for all fitness levels in small groups.",issues:["No website — class info only on Instagram","No online class booking or timetable","A professional site with booking integration would reduce admin work"]},
  {id:77,name:"Thornlie Tyre Service",category:"Tyres",suburb:"Thornlie",phone:"(08) 9493 3388",email:"",website:"",contactForm:false,desc:"Tyre sales, fitting, balancing, and wheel alignment service in Thornlie covering passenger and 4WD vehicles.",issues:["No website — customers searching for tyres find competitors","No tyre brand or pricing info online","A site with tyre search by vehicle would be a game-changer"]},
  {id:78,name:"Kalamunda Garden Centre",category:"Garden Centre",suburb:"Kalamunda",phone:"(08) 9293 1855",email:"",website:"",contactForm:false,desc:"Independent garden centre in Kalamunda selling native plants, pots, soil, and gardening supplies for the hills area.",issues:["No website — missing seasonal gardening searches","No online product catalogue","A site with planting guides and store events would build community loyalty"]},
  {id:79,name:"Bull Creek Tutoring",category:"Education",suburb:"Bull Creek",phone:"0422 111 445",email:"bctutor@gmail.com",website:"",contactForm:false,desc:"Private tutoring service in Bull Creek offering maths, English, and science tutoring for primary and high school students.",issues:["No website — parents search online for local tutors","No subject info or tutor qualifications published","A professional site with testimonials would build trust with parents"]},
  {id:80,name:"Parkwood Sewing Centre",category:"Retail",suburb:"Parkwood",phone:"(08) 9457 1133",email:"",website:"",contactForm:false,desc:"Sewing machine sales and repairs shop in Parkwood selling fabrics, patterns, and haberdashery supplies.",issues:["No website — sewing enthusiasts shop online","No product catalogue or class offerings","An e-commerce presence would expand beyond local foot traffic"]},
  {id:81,name:"Ferndale Auto Detailing",category:"Auto Detailing",suburb:"Ferndale",phone:"0418 999 332",email:"ferndale.detail@gmail.com",website:"",contactForm:false,desc:"Mobile and workshop car detailing service in Ferndale offering paint correction, ceramic coating, and interior deep cleaning.",issues:["No website — detailing is heavily searched online","No before/after photo gallery","A portfolio site with pricing packages would convert browsers to bookings"]},
  {id:82,name:"Shelley Bridge Club",category:"Recreation",suburb:"Shelley",phone:"(08) 9354 2255",email:"",website:"shelleybridgeclub.org.au",contactForm:true,desc:"Community bridge club in Shelley running weekly sessions, lessons for beginners, and tournament play for experienced players.",issues:["Website is extremely dated with 1990s-era design","No online event calendar or results","A modern refresh with member portal would attract younger members"]},
  {id:83,name:"Byford Pizza & Pasta",category:"Restaurant",suburb:"Byford",phone:"(08) 9525 4422",email:"",website:"",contactForm:false,desc:"Italian-style pizza and pasta restaurant in Byford with dine-in, takeaway, and delivery to surrounding suburbs.",issues:["No website — menu only visible on Menulog/UberEats","No branded online ordering platform","A custom site with online ordering would save on third-party commissions"]},
  {id:84,name:"Armadale Dance Academy",category:"Dance",suburb:"Armadale",phone:"(08) 9399 5511",email:"info@armadaledance.com.au",website:"armadaledance.com.au",contactForm:true,desc:"Dance school in Armadale teaching ballet, jazz, hip-hop, and contemporary to children and teens across the southeast.",issues:["Website is a basic template with broken image links","No timetable or fee information visible","Missing enrolment form and parent portal"]},
  {id:85,name:"Canning River Canoe Hire",category:"Recreation",suburb:"Riverton",phone:"0422 333 556",email:"canoeperth@gmail.com",website:"",contactForm:false,desc:"Kayak and canoe hire operating on the Canning River, offering guided and self-guided paddling experiences.",issues:["No website — tourism and activity searches go to competitors","No online booking or availability calendar","A visual site with route maps and booking would boost summer revenue"]},
  {id:86,name:"Wattle Grove Bakery",category:"Bakery",suburb:"Wattle Grove",phone:"(08) 9453 3311",email:"",website:"",contactForm:false,desc:"Suburban bakery in Wattle Grove selling fresh bread, pies, pastries, and custom cakes for local residents.",issues:["No website — bakery products are heavily searched online","No cake ordering system or custom cake gallery","A simple site with ordering form and cake portfolio would drive business"]},
  {id:87,name:"Kenwick Auto Electrical",category:"Auto Electrician",suburb:"Kenwick",phone:"(08) 9459 4422",email:"",website:"",contactForm:false,desc:"Auto electrical specialist in Kenwick handling car alarms, stereo installs, alternator repairs, and diagnostic scanning.",issues:["No web presence at all","No service list or pricing info online","A basic site with clear services would capture local search traffic"]},
  {id:88,name:"Gosnells Laundromat",category:"Laundry",suburb:"Gosnells",phone:"(08) 9490 2211",email:"",website:"",contactForm:false,desc:"Self-service laundromat in Gosnells with commercial washers, dryers, and a drop-off wash-and-fold service.",issues:["No website — customers can't check operating hours online","No pricing or machine availability info","A Google-optimised page with hours and pricing would reduce phone calls"]},
  {id:89,name:"Lesmurdie Falls Cafe",category:"Cafe",suburb:"Lesmurdie",phone:"(08) 9291 2244",email:"",website:"",contactForm:false,desc:"Cafe near Lesmurdie Falls serving hikers and day-trippers with coffee, breakfast, and lunch in a bushland setting.",issues:["No website — missing tourism and hiking search traffic","No menu or operating hours published online","A scenic site with trail info would attract visitors planning hikes"]},
  {id:90,name:"Maddington Glass & Glazing",category:"Glazier",suburb:"Maddington",phone:"(08) 9493 7722",email:"madglass@bigpond.com",website:"",contactForm:false,desc:"Glass repair and installation service in Maddington covering windows, shower screens, mirrors, and security glass.",issues:["No website — emergency glass repair is heavily Googled","No online quote form or service area map","A mobile-optimised site with emergency contact would capture after-hours leads"]},
  {id:91,name:"Kelmscott Veterinary Hospital",category:"Vet",suburb:"Kelmscott",phone:"(08) 9390 2422",email:"reception@kelmscottvet.com.au",website:"kelmscottvet.com.au",contactForm:true,desc:"Full-service veterinary hospital in Kelmscott offering surgery, dental, radiology, and 24-hour emergency pet care.",issues:["Website is functional but design is very dated","No online appointment booking","Missing pet owner resource section and blog"]},
  {id:92,name:"Gosnells Soccer Club",category:"Sports Club",suburb:"Gosnells",phone:"(08) 9490 6611",email:"info@gosnellsfc.com.au",website:"gosnellsfc.com.au",contactForm:true,desc:"Community soccer club in Gosnells running junior, senior, and social leagues throughout the football season.",issues:["Website has outdated fixture info and broken links","No online registration or payment","Missing photo gallery and social media integration"]},
  {id:93,name:"Cannington Alterations",category:"Tailoring",suburb:"Cannington",phone:"(08) 9356 5577",email:"",website:"",contactForm:false,desc:"Clothing alterations and tailoring service in Cannington handling hems, suits, wedding dress adjustments, and repairs.",issues:["No website — alterations are frequently searched locally","No portfolio of work or pricing guide","A simple site with pricing and turnaround times would convert"]},
  {id:94,name:"Forrestfield Gym",category:"Fitness",suburb:"Forrestfield",phone:"(08) 9453 8811",email:"info@forrestfieldgym.com.au",website:"forrestfieldgym.com.au",contactForm:true,desc:"Independent gym in Forrestfield with weights, cardio, group fitness classes, and personal training services.",issues:["Website is a basic WordPress template with broken gallery","No online membership sign-up or class timetable","Missing virtual tour of facilities and trainer profiles"]},
  {id:95,name:"Thornlie Chinese Restaurant",category:"Restaurant",suburb:"Thornlie",phone:"(08) 9493 2288",email:"",website:"",contactForm:false,desc:"Long-running Chinese restaurant in Thornlie serving Cantonese favourites, banquet menus, and takeaway to the local area.",issues:["No website — menu only on third-party delivery apps","No online ordering to avoid delivery app commissions","A branded site with loyalty program would increase direct orders"]},
  {id:96,name:"Beckenham Podiatry",category:"Health",suburb:"Beckenham",phone:"(08) 9356 9944",email:"admin@beckhampod.com.au",website:"beckhampod.com.au",contactForm:true,desc:"Podiatry practice in Beckenham treating foot pain, ingrown toenails, orthotics fitting, and diabetic foot assessments.",issues:["Website is outdated with stock medical photos","No online appointment booking","Missing condition-specific pages for SEO"]},
  {id:97,name:"Wattle Grove Childcare",category:"Childcare",suburb:"Wattle Grove",phone:"(08) 9453 7755",email:"",website:"",contactForm:false,desc:"Family day care service in Wattle Grove providing care for children aged 0-5 in a home-based nurturing environment.",issues:["No website — parents searching for childcare go elsewhere","No info on curriculum, fees, or vacancies online","A professional site with enrolment waitlist would fill spots faster"]},
  {id:98,name:"Armadale Picture Framing",category:"Retail",suburb:"Armadale",phone:"(08) 9399 3388",email:"",website:"",contactForm:false,desc:"Custom picture framing and art supply shop in Armadale offering frames, mats, and canvas stretching services.",issues:["No online presence at all","No portfolio or pricing guide","A gallery site with online ordering would expand their reach"]},
  {id:99,name:"Southern Hills Electrical",category:"Electrician",suburb:"Bedfordale",phone:"0433 111 778",email:"southernhillselec@gmail.com",website:"",contactForm:false,desc:"Licensed electrician serving Bedfordale, Armadale, and the Perth Hills for residential and light commercial electrical work.",issues:["No website — electrical services are heavily searched online","No service area map or emergency contact info","A mobile-optimised site with click-to-call is essential for tradies"]},
  {id:100,name:"Camillo Takeaway",category:"Takeaway",suburb:"Camillo",phone:"(08) 9496 2233",email:"",website:"",contactForm:false,desc:"Classic Aussie takeaway shop in Camillo selling burgers, fish and chips, schnitzels, and milkshakes to the local community.",issues:["No website or any online presence","No menu published anywhere online","A simple menu page with hours and location would capture search traffic"]}
];
